config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :teams
  post 'team_users/edit_multiple'
  put 'team_users/update_multiple'
  resources :user_profile
  resources :projects
  resources :sprints, except: [:index]
  resources :activities, except: [:index]
  resources :colors, except: [:show]
  resources :labels, except: [:show]
  resources :statuses, except: [:show]
  resources :macro_activities, except: [:index, :show]
  resources :sub_macro_activities, except: [:show]
  resources :progresses, except: [:show, :edit, :update]
  resources :weeks, only: [:edit, :update]


  resources :reports, only: [:index]
  namespace :reports do
    resources :weeks_reports, only: [:index]
    get '/weeks_reports/relative_dedication' => 'weeks_reports#relative_dedication'
    get '/weeks_reports/team_monitoring' => 'weeks_reports#team_monitoring'
    resources :sprints_reports, only: [:index]
    get '/sprints_reports/relative_dedication' => 'sprints_reports#relative_dedication'
    get '/sprints_reports/activities_list' => 'sprints_reports#activities_list'
    get '/sprints_reports/advance_and_completeness' => 'sprints_reports#advance_and_completeness'
    get '/sprints_reports/team_monitoring' => 'sprints_reports#team_monitoring'
    get '/sprints_reports/relative_productivity' => 'sprints_reports#relative_productivity'
  end

  post '/projects/:id/login', to: 'hours_registries#login', as: 'project_login'
  put '/projects/:id/logout', to: 'hours_registries#logout', as: 'project_logout'

  get 'home/index'
  root 'home#index'
  # resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reports/sprints_reports_controller.rb
class Reports::SprintsReportsController < ReportsController
  def index
  end

  def relative_dedication
    respond_to do |format|
      format.pdf do
        render pdf: "report",
               disposition: "inline",
               template: "reports/sprints_reports/relative_dedication.html.erb",
               orientation: 'Landscape',
               layout: "report_pdf",
               locals: { :@sprint => Sprint.find(params[:sprint]),
                         :@observation => params[:observation] },
               page_size: 'A4',
               encoding: 'utf8'
      end
      format.html do
        render template: "reports/sprints_reports/relative_dedication.html.erb",
               layout: "report_pdf",
               locals: { :@sprint => Sprint.find(params[:sprint]),
                         :@observation => params[:observation] }
       end
    end
  end

  def activities_list
    respond_to do |format|
      format.pdf do
        render pdf: "report",
               disposition: "inline",
               template: "reports/sprints_reports/activities_list.html.erb",
               orientation: 'Landscape',
               layout: "report_pdf",
               locals: { :@observation => params[:observation] },
               page_size: 'A4',
               encoding: 'utf8'
      end
      format.html do
        render template: "reports/sprints_reports/activities_list.html.erb",
               layout: "report_pdf",
               locals: { :@observation => params[:observation] }
       end
    end
  end

  def advance_and_completeness
    respond_to do |format|
      format.pdf do
        render pdf: "report",
               disposition: "inline",
               template: "reports/sprints_reports/advance_and_completeness.html.erb",
               orientation: 'Landscape',
               layout: "report_pdf",
               locals: { :@sprint => Sprint.find(params[:sprint]),
                         :@observation => params[:observation] },
               page_size: 'A4',
               encoding: 'utf8'
      end
      format.html do
        render template: "reports/sprints_reports/advance_and_completeness.html.erb",
               layout: "report_pdf",
               locals: { :@sprint => Sprint.find(params[:sprint]),
                         :@observation => params[:observation] }
       end
    end
  end

  def team_monitoring
    respond_to do |format|
      format.pdf do
        render pdf: "report_#{Sprint.find(params[:sprint]).description}",
               disposition: "inline",
               template: "reports/sprints_reports/team_monitoring.html.erb",
               layout: "report_pdf",
               locals: { :@sprint => Sprint.find(params[:sprint]),
                         :@observation => params[:observation] },
               page_size: 'A4',
               encoding: 'utf8'
      end
      format.html do
        render template: "reports/sprints_reports/team_monitoring.html.erb",
               layout: "report_pdf",
               locals: { :@sprint => Sprint.find(params[:sprint]),
                         :@observation => params[:observation] }
       end
    end
  end

  def relative_productivity
    respond_to do |format|
      format.pdf do
        render pdf: "report",
               disposition: "inline",
               template: "reports/sprints_reports/relative_productivity.html.erb",
               orientation: 'Landscape',
               layout: "report_pdf",
               locals: { :@observation => params[:observation] },
               page_size: 'A4',
               encoding: 'utf8'
      end
      format.html do
        render template: "reports/sprints_reports/relative_productivity.html.erb",
               layout: "report_pdf",
               locals: { :@sprint => Sprint.find(params[:sprint]),
                         :@observation => params[:observation] }
       end
    end
  end

  def relative_velocity
    respond_to do |format|
      format.pdf do
        render pdf: "report",
               disposition: "inline",
               template: "reports/sprints_reports/relative_velocity.html.erb",
               orientation: 'Landscape',
               layout: "report_pdf",
               locals: { :@sprint => Sprint.find(params[:sprint]),
                         :@observation => params[:observation] },
               page_size: 'A4',
               encoding: 'utf8'
      end
      format.html do
        render template: "reports/sprints_reports/relative_velocity.html.erb",
               layout: "report_pdf",
               locals: { :@sprint => Sprint.find(params[:sprint]),
                         :@observation => params[:observation] }
       end
    end
  end
end

app/controllers/reports/weeks_reports_controller.rb
class Reports::WeeksReportsController < ReportsController

  def index

  end

  def relative_dedication
    respond_to do |format|
      format.pdf do
        render pdf: "report",
               disposition: "inline",
               template: "reports/weeks_reports/relative_dedication.html.erb",
               orientation: 'Landscape',
               layout: "report_pdf",
               locals: { :@sprint => Sprint.find(params[:sprint]),
                         :@observation => params[:observation] },
               page_size: 'A4',
               encoding: 'utf8'
      end
      format.html do
        render template: "reports/weeks_reports/relative_dedication.html.erb",
               layout: "report_pdf",
               locals: { :@sprint => Sprint.find(params[:sprint]),
                         :@observation => params[:observation] }
       end
    end
  end

  def team_monitoring
    respond_to do |format|
      format.pdf do
        render pdf: "report_#{Sprint.find(params[:sprint]).description}",
               disposition: "inline",
               template: "reports/weeks_reports/team_monitoring.html.erb",
               layout: "report_pdf",
               locals: { :@sprint => Sprint.find(params[:sprint]),
                         :@observation => params[:observation] },
               page_size: 'A4',
               encoding: 'utf8'
      end
      format.html do
        render template: "reports/weeks_reports/team_monitoring.html.erb",
               layout: "report_pdf",
               locals: { :@sprint => Sprint.find(params[:sprint]),
                         :@observation => params[:observation] }
       end
    end
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
  end
end

app/helpers/reports/sprints_reports_helper.rb
module Reports::SprintsReportsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/index.html.erb
<div class="col-lg-9">
  <div class="panel">

    <div class="panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><center>Listagem dos Relatórios</center></h3>
      </div>
    </div>

    <div class="panel-body">

      <div class="row">

        <div class="col-lg-6 col-sm-6">
          <%= link_to reports_weeks_reports_path do %>
            <div class="img-reports">
              <%= image_tag 'relatorio semanal.png' %>
            </div>
          <% end %>
          <br>
          <p class="description" style="text-align: justify; margin: 5px 10px;">
            Relatório semanal da dedicação relativa por usuário, até a semana
            corrente da Sprint selecionada; dedicação relativa por equipe,
            velocidade de pontos realizados e burndown, até a semana corrente da
            Sprint selecionada.
          </p>
          <div class="centered">
            <%= link_to "Relatórios semanais", reports_weeks_reports_path, class: 'btn btn-default' %>
          </div>
        </div>

        <div class="col-lg-6 col-sm-6">
          <%= link_to reports_sprints_reports_path do %>
            <div class="img-reports">
              <%= image_tag 'relatorio de sprint.PNG' %>
            </div>
          <% end %>
          <br>
          <p class="description" style="text-align: justify; margin: 5px 10px;">
            Relatório de final de Sprint da dedicação relativa por usuário em
            cada semana da Sprint finalizada; lista de atividades feitas vs
            atividades propostas de cada projeto, de acordo com o seu tipo;
            gráfico de completo e avanço de cada equipe; dedicação relativa por
            equipe, velocidade de pontos realizados e burndown, até a semana
            corrente da Sprint finalizada.
          </p>
          <div class="centered">
            <%= link_to "Relatórios de sprint", reports_sprints_reports_path, class: 'btn btn-default' %>
          </div>
        </div>

      </div>

    </div>

  </div>
</div>

<script>
  $(document).ready(function($) {
    $('.description').readmore({
      speed: 100,
      embedCSS: false,
      collapsedHeight: 80,
      moreLink: '<a href="#">Ler mais...</a>',
      lessLink: '<a href="#">Fechar</a>'
    });
  });
</script>